modLoader="javafml"
loaderVersion="[58,)"
license="MIT"
[[mods]]
modId="soulboundblock"
version="1.0.0"
displayName="Soulbound Block"
description='''Bloque soulbound de prueba'''
authors="Banzaicode"
